# Setup
title:               SETI.news
tagline:             'The latest in SETI research'
description:         'A newsletter collecting the latest in academic SETI research.'
url:                 https://SETI.news
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              James R. A. Davenport
  url:               https://twitter.com/jradavenport
  email:             jrad@uw.edu

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

logo: '/public/s.png'